### ISSUE TITLE
error output checking 

### ISSUE THREAD

**Issue by mustafasaydam** [sametbirol/BLG223E_ITU_2024_FALL#1]
- case_2:
        run: ./main ./employee_salaries.csv ./operations2.txt #timeout: 5
        script:
          - expect: 'ERROR: An invalid ID to delete(\r\n)*ERROR: An invalid ID to update(\r\n)*ERROR: An invalid ID to update' #timeout: 5
        blocker: true
- test_2:
        run: diff --strip-trailing-cr ./solution2.csv ./array_solution.csv
        
        points: 10

**Comment by sametbirol** [comment]
Everything is prepared, but I'm facing an issue where the regex doesn't match as expected. I'm currently waiting for a response from the TA to address this.

**Comment by sametbirol** [comment]
Due to my inability to effectively match newline patterns in regular expressions ('\\n', '\\r\\n', 'endl'), and given that the Assistant has clarified that error output checking is not handled by Calico, I plan to release test cases with error conditions in a new YAML file. Before testing with this file, please ensure that any newline printing is removed from your code.
